package com.squad.musicmatters.core.model


data class UserData(
    val fontName: String,
    val fontScale: Float,
    val themeMode: ThemeMode,
    val useMaterialYou: Boolean,
    val primaryColorName: String,
    val bottomBarLabelVisibility: BottomBarLabelVisibility,
    val fadePlayback: Boolean,
    val fadePlaybackDuration: Float,
    val requireAudioFocus: Boolean,
    val ignoreAudioFocusLoss: Boolean,
    val playOnHeadphonesConnect: Boolean,
    val pauseOnHeadphonesDisconnect: Boolean,
    val miniPlayerTextMarquee: Boolean,
    val loopMode: LoopMode,
    val shuffle: Boolean,
    val showLyrics: Boolean,
    val currentlyDisabledTreePaths: Set<String>,
    val sortSongsBy: SortSongsBy,
    val sortSongsReverse: Boolean,
    val sortArtistsBy: SortArtistsBy,
    val sortArtistsReverse: Boolean,
    val sortGenresBy: SortGenresBy,
    val sortGenresReverse: Boolean,
    val sortPlaylistsBy: SortPlaylistsBy,
    val sortPlaylistsReverse: Boolean,
    val sortAlbumsBy: SortAlbumsBy,
    val sortAlbumsReverse: Boolean,
    val sortPathsBy: SortPathsBy,
    val sortPathsReverse: Boolean,
    val currentlyPlayingSongId: String,
    val showLyricsOnSeparateScreen: Boolean,
)
